ALTER TABLE test1 ENABLE REPLICATION;
ALTER TABLE test2 ENABLE REPLICATION;
ALTER TABLE test1 ENABLE REPLICATION ON SLAVE 0;
ALTER TABLE test2 ENABLE REPLICATION ON SLAVE 0;
ALTER TABLE test1 ENABLE REPLICATION ON SLAVE 1;
ALTER TABLE test2 ENABLE REPLICATION ON SLAVE 1;
ALTER TABLE test1 ENABLE REPLICATION ON SLAVE 2;
ALTER TABLE test2 ENABLE REPLICATION ON SLAVE 2;
