ALTER TABLE branches ENABLE REPLICATION;
ALTER TABLE accounts ENABLE REPLICATION;
ALTER TABLE tellers ENABLE REPLICATION;
ALTER TABLE history ENABLE REPLICATION;

ALTER TABLE branches ENABLE REPLICATION ON SLAVE 0;
ALTER TABLE accounts ENABLE REPLICATION ON SLAVE 0;
ALTER TABLE tellers ENABLE REPLICATION ON SLAVE 0;
ALTER TABLE history ENABLE REPLICATION ON SLAVE 0;

ALTER TABLE branches ENABLE REPLICATION ON SLAVE 1;
ALTER TABLE accounts ENABLE REPLICATION ON SLAVE 1;
ALTER TABLE tellers ENABLE REPLICATION ON SLAVE 1;
ALTER TABLE history ENABLE REPLICATION ON SLAVE 1;

ALTER TABLE branches ENABLE REPLICATION ON SLAVE 2;
ALTER TABLE accounts ENABLE REPLICATION ON SLAVE 2;
ALTER TABLE tellers ENABLE REPLICATION ON SLAVE 2;
ALTER TABLE history ENABLE REPLICATION ON SLAVE 2;
