SELECT * FROM test1 ORDER BY col1;
SELECT * FROM test2 ORDER BY col1;
SELECT * FROM test3 ORDER BY col1;
SELECT * FROM test4 ORDER BY col1;
SELECT * FROM test5 ORDER BY a;
SELECT * FROM test6 ORDER BY a;
SELECT * FROM test7 ORDER BY a;
SELECT * FROM test8 ORDER BY a;
SELECT count(col1), sum(col1), max(col3) FROM test9;
SELECT count(col1), sum(col1), max(col3) FROM test10 WHERE col2='updated';
SELECT * FROM test11;
SELECT count(col1), sum(col1), max(col3) FROM test12 WHERE col2='updated';
SELECT * FROM test13 ORDER BY col1;
SELECT * FROM test14 ORDER BY col1;
SELECT * FROM test15 ORDER BY col1;
SELECT * FROM test16 ORDER BY col1;
SELECT * FROM test17 ORDER BY col1;
SELECT count(col1), sum(col1), max(col3) FROM test18;
SELECT * FROM test19 ORDER BY col0,col1,col2,col4;
SELECT * FROM test20_1 UNION SELECT * FROM test20_2 UNION SELECT * FROM test20_3 ORDER BY col1;
SELECT * FROM test21 ORDER BY col1,col3;
SELECT * FROM test22 ORDER BY col1,col3;
SELECT * FROM test23 ORDER BY col1,col3;
SELECT * FROM test24 ORDER BY col1,col3;
SELECT * FROM test25 ORDER BY col1,col3;
SELECT * FROM test26 ORDER BY col1,col3;
SELECT * FROM test27 ORDER BY col1,col3;
SELECT * FROM test28_1 ORDER BY col1;
SELECT * FROM test28_2 ORDER BY col1;
SELECT * FROM test29 ORDER BY col1;
SELECT * FROM test30 ORDER BY col1;
SELECT * FROM test31 ORDER BY col1;
SELECT * FROM test32 ORDER BY col1;
SELECT * FROM test33 ORDER BY col1;
SELECT * FROM test34 ORDER BY col1;
SELECT * FROM test35 ORDER BY col1;
SELECT * FROM test36 ORDER BY col1;
SELECT length(col2) FROM test37 ORDER BY col1;
SELECT length(col2) FROM test38 ORDER BY col1;
SELECT * FROM test39 ORDER BY col1;
SELECT COUNT(*), CASE WHEN COUNT(*)=0 THEN now()::text ELSE '' END FROM test40;

