#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for mammoth_r/common
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

subdir = src/backend/mammoth_r/common
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = mcp_api.o mcp_queue.o mcp_compress.o \
   	   mcp_connection.o mcp_file.o common_tables.o \
	   backend_tables.o mcp_lists.o txlog.o

include $(top_srcdir)/src/backend/common.mk
