# Makefile for /src/backend/mammoth_r/globals/
# functions for C triggers to replicate globals

subdir = src/backend/mammoth_r/globals
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = pgr_acl.o pgr_authid.o pgr_auth_members.o pgr_relations.o \
 	   repl_roles_trigger.o

include $(top_srcdir)/src/backend/common.mk
